### ISSUE TITLE
what is this problem?

### ISSUE THREAD

**Issue by xeon-a** [Saket-Upadhyay/Android-Permission-Extraction-and-Dataset-Creation-with-Python#6]
Traceback (most recent call last):
  File "ExtractorAIO.py", line 210, in <module>
    Main()
  File "ExtractorAIO.py", line 195, in Main
    Extract()
  File "ExtractorAIO.py", line 89, in Extract
    root = ET.parse(MainfestPath).getroot()
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

i tried this code with some malware apk from 'CICANDMAL 2017'
what is this problem????

**Comment by LuShuo-fighting** [comment]
![image](https://user-images.githubusercontent.com/32241034/202769502-7f7b0cda-3ffc-4a44-815b-365c53f45b52.png)
The generated csv file has no data
